package:
  name: activated-shell
  version: "0.1.0"

build:
  noarch: generic
  script:
    - mkdir -p $PREFIX/Menu
    - cp $RECIPE_DIR/menu/menu.json $PREFIX/Menu/pixi-editor.json
    - cp $RECIPE_DIR/../../icons/pixi-icon.* $PREFIX/Menu/
    - mkdir -p "${PREFIX}/etc/conda/activate.d"
    - cp $RECIPE_DIR/activate.sh "${PREFIX}/etc/conda/activate.d/pixi-editor-activate.sh"